# Generated by Django 5.1 on 2024-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
