# Generated by Django 5.1 on 2024-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_concert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='max_ticket',
            field=models.IntegerField(default=1),
        ),
    ]
