# Generated by Django 5.1 on 2024-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticket_concert_remove_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
