# Generated by Django 5.1 on 2024-09-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_price_ticket_purchaser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
