# Generated by Django 5.1 on 2024-09-02 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='card_number',
            field=models.CharField(default='0000000000000000', help_text='Enter the card number without spaces or dashes.', max_length=19, validators=[django.core.validators.RegexValidator(message='Card number must be between 13 and 19 digits.', regex='^\\d{13,19}$')]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
